-- Use the northwind database to answer each question.

-- PART 1
-- What is the name of the employee with the highest number of orders?
-- ANSWER: MARGARET PEACOCK (156)
SELECT E.EMPLOYEENAME, COUNT(O.ORDERID) AS TOTAL_ORDERS
FROM EMPLOYEES E
	INNER JOIN ORDERS O USING (EMPLOYEEID)
GROUP BY E.EMPLOYEENAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 1;


-- PART 2
-- What is the name of the employee with the highest dollar amount of sales? You can ignore the discount column when answering this.
-- ANSWER: MARGARET PEACOCK ($250,187.45)
SELECT E.EMPLOYEENAME, ROUND(SUM(D.UNITPRICE * D.QUANTITY), 2) AS TOTAL_ORDER_PRICE
FROM EMPLOYEES E
	INNER JOIN ORDERS O USING (EMPLOYEEID)
	INNER JOIN ORDER_DETAILS D USING (ORDERID)
GROUP BY E.EMPLOYEENAME
ORDER BY TOTAL_ORDER_PRICE DESC
LIMIT 1;


-- PART 3
-- What is the name of the employee who has sold the highest quantity of Grandma's Boysenberry Spread?
-- ANSWER: NANCY DAVOLIO (93)
SELECT E.EMPLOYEENAME, SUM(D.QUANTITY) AS TOTAL_QUANTITY
FROM EMPLOYEES E
	INNER JOIN ORDERS O USING (EMPLOYEEID)
	INNER JOIN ORDER_DETAILS D USING (ORDERID)
	INNER JOIN PRODUCTS P USING (PRODUCTID)
WHERE P.PRODUCTNAME = 'Grandma''s Boysenberry Spread'
GROUP BY E.EMPLOYEENAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 1;

-- PART 4
-- Find the name of the employee with the most number of orders which included an item from the Beverages category.
-- ANSWER: MARGARET PEACKOCK (65)
SELECT E.EMPLOYEENAME, COUNT(DISTINCT O.ORDERID) AS TOTAL_ORDERS
FROM EMPLOYEES E
	INNER JOIN ORDERS O USING (EMPLOYEEID)
	INNER JOIN ORDER_DETAILS D USING (ORDERID)
	INNER JOIN PRODUCTS P USING (PRODUCTID)
	INNER JOIN CATEGORIES C USING (CATEGORYID)
WHERE C.CATEGORYNAME = 'Beverages'
GROUP BY E.EMPLOYEENAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 1;


-- PART 5
-- Is there any category for which Margaret Peacock does not have the highest number of orders including an item from that category?
-- ANSWER: DAIRY PRODUCTS - NANCY DAVOLIO, PRODUCE - NANCY DAVOLIO
SELECT DISTINCT ON (C.CATEGORYNAME) C.CATEGORYNAME, E.EMPLOYEENAME, COUNT(DISTINCT O.ORDERID) AS TOTAL_ORDERS
FROM EMPLOYEES E
	INNER JOIN ORDERS O USING (EMPLOYEEID)
	INNER JOIN ORDER_DETAILS D USING (ORDERID)
	INNER JOIN PRODUCTS P USING (PRODUCTID)
	INNER JOIN CATEGORIES C USING (CATEGORYID)
GROUP BY C.CATEGORYNAME, E.EMPLOYEENAME
ORDER BY C.CATEGORYNAME, TOTAL_ORDERS DESC;