-- PART 1
-- How many different customers are there?

-- ANSWER: There are 91 distinct customers.
SELECT COUNT(DISTINCT CUSTOMERID) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;


-- PART 2
-- Which city has the most customers?

-- ANSWER: London has the most customers
SELECT CITY, COUNT(DISTINCT CUSTOMERID) AS TOTAL_CUSTOMERS
FROM CUSTOMERS
GROUP BY CITY
ORDER BY TOTAL_CUSTOMERS DESC
LIMIT 1;


-- PART 3
-- Find all orders with an orderdate in May of 2014.
-- HINT: You can use the EXTRACT function (https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) to get the month and year from the order date.

-- ANSWER: 32 orders
SELECT ORDERID, ORDERDATE
FROM ORDERS
WHERE EXTRACT(MONTH FROM ORDERDATE) = 5
	AND EXTRACT(YEAR FROM ORDERDATE) = 2014
ORDER BY ORDERDATE;


-- PART 4
-- Find all company names for customers who had an order in May of 2014.

-- ANSWER: 26 companies
SELECT DISTINCT C.COMPANYNAME
FROM ORDERS O
	LEFT JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE EXTRACT(MONTH FROM ORDERDATE) = 5
	AND EXTRACT(YEAR FROM ORDERDATE) = 2014
ORDER BY COMPANYNAME;


-- PART 5
-- Find all company names for customers who had an order in May of 2014 but did not have an order in June of 2014.

-- ANSWER: 19 companies
-- SUBQUERY VERSION
SELECT DISTINCT C.COMPANYNAME
FROM ORDERS O
	LEFT JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE EXTRACT(MONTH FROM ORDERDATE) = 5
	AND EXTRACT(YEAR FROM ORDERDATE) = 2014
	AND C.COMPANYNAME NOT IN (SELECT DISTINCT C.COMPANYNAME
								FROM ORDERS O
									LEFT JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
								WHERE EXTRACT(MONTH FROM O.ORDERDATE) = 6
									AND EXTRACT(YEAR FROM O.ORDERDATE) = 2014)
ORDER BY COMPANYNAME;

-- 'EXCEPT' VERSION
SELECT DISTINCT C.COMPANYNAME
FROM ORDERS O
	LEFT JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE EXTRACT(MONTH FROM ORDERDATE) = 5
	AND EXTRACT(YEAR FROM ORDERDATE) = 2014
EXCEPT
SELECT DISTINCT C.COMPANYNAME
FROM ORDERS O
	LEFT JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE EXTRACT(MONTH FROM O.ORDERDATE) = 6
	AND EXTRACT(YEAR FROM O.ORDERDATE) = 2014
ORDER BY COMPANYNAME;